jobs:
    include:
        - language: php
          php: '7.3'
          script:
          - cd symfony
          - composer install
          - make ci
          after_success:
          - bash <(curl -s https://codecov.io/bash)
        - language: node_js
          node_js: 10
          script:
          - cd vue
          - yarn install
          - make ci
